# fly.toml app configuration file generated for brg-mn on 2024-11-29T07:01:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brg-mn'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
[env]
  LOG_MODE = 'short'
  PORT = 8080

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
